### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by MrKrishnaAgarwal** [UG-SEP/Tenthies#31]
Your website is not visible @UG-SEP

**Comment by UG-SEP** [comment]
I apologize for it but tenthies is temporarily closed due to insufficient
money to host the website.

You can visit our Eduwallaa <https://eduwallaa.com> Website where we
provide educational content blogs related to science, technology, and
guidance.

Thank you

**Comment by MrKrishnaAgarwal** [comment]
Okay
No issues 
Thanks for informing
Closing this issue with good luck 👍🏻

**Comment by UG-SEP** [comment]
Thank you!
